sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-020.pdf --upload --lsstdoc DMTN-020.tex --env=travis --ltd-product $PRODUCT"
env:
  global:
    - PRODUCT="dmtn-020"
    # Add LSST the Docs credentials
    - secure: "xHGey2Fty9XqSEEUzwURddLCQTZQxp8R/mROCAF9OCIOdVBTd0Hzc3Pa+A5btfy3WPlcqalu3NUnCP7Oz6/NqiccYhwAqll/eZez+LU9UZJQCyHleLedC/D3aewESTACUjdZXuUsMe6wyeEJdKJneEZ5x9CjcTXGJWGgi2AE61pYNOYHi576teI8btVaOwLyhXuSRFw53L/6zQY/1Yme0HpRB4gfhUi3RKjYMMX/6qfTZqOOeY5cx14PtKL2vKENG1bJia0188G9LhTG5Winn5sgRDAX+VbUOdYKi+esgic/iJE9je2JTHMEbJ3r/7rg7FZ+tRhGNhYyc7KSs9hU8uC/BqiHFi1UPvrJ6faTb0fwh4uK8fhZN3hwsf6hcYI0W8U+IpFPd/H6tNNdp32i2zGtsAYuirRBGAndolIwi6nXFdmFqnWdQQ+HmS6VlH+zn4CDKzCcmtmHDaTk0VJYIbgJn3S5+kLsSMSuBDs9yaNuSSApb38LfGg8wQEJPCOeJB1aaj+aTIJJaSQ7idzXugkRvSN2FBPgZnL5m1YtjBpLXVepVx1L8irJ57e1qNscB8aSFx3ZcgLiBX33iKSGXJ0AXZPVemQzpSmIXF/0/cO96q8r/IFZnlF/lbl42+2bHKyWuMpwysM9y56iW09EbhjCh7l6KwsF/hEPKc17L4Q="
    - secure: "iXJJxGWYkcN7gO2+5TtEBcl0DdfQNAEQ2C3HAV1yL7gvQDWBxNirM56EbpTe1+qt2wNlxnabB4OT2cvXd0c9U7ismVTXntCjznljS9u62KztwBY9joUwbgT+Jz287bOXfGbIXx/4WqhUSweBqui8RrbiTyWqEaQrlnXTx9/BneDihvzqHEcBzEgDd6PlI3/9ksDoW/xw/x2cXPZsFIIb+MmDb9Xz4O2d1T/J3oJgTErz1eNkIPSdEyi++FnWPJdERK29RUp+xKQDkIEQtFK7vBbUjNpCLvZuGaTPI/MYZOIsrhBABXEu26OQiQySCHL9KeE8x3yQKvEXt2byrG2e0rJjXrZZa990h1XvSxVp6crkHCwxu/RDAMCMFNltMtuB/JQFXQm5wTgnnt5TEEzilWfBsF01mM8Y8+iHLHUj/QH04VTdp1A2voxjAet6u61PivqdKlrVlFrIhxSBP6pTK4ENLcR+bEDmZjpxtrGaHmEMb0cWtuMq+BnsPIn9pcyAByskiml53JvB1CknIQnAc6o726j8RjNIz3tFZ1si1Afhw1pZYydQWRtX93KIq2abYPkbEmyaks+YLjeXEPS7JdehrMgQf+BcYvcajDUxBaeF1fwXGMBh8NbQev/kZir9mFd61pwGnIxvMtLTfZGtbrGAkBB+TGUbsFl5k6b/gG4="
